# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: empresajuniro
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: odin-plataform
# serverless.yml

name: odin-next-app
component: "@sls-next/serverless-component@3.8.0"

inputs:
  region: sa-east-1
  memory: 1024
  timeout: 30
  runtime: nodejs18.x
  architecture: arm64
  useServerlessTraceTarget: true
  nextConfigDir: ./ # ou o caminho se seu next.config.js estiver em outra pasta
  bucketName: odin-platform-deploy
  environment:
    DATABASE_URL: ${env:DATABASE_URL}
    AWS_S3_BUCKET_NAME: ${env:AWS_S3_BUCKET_NAME}
    AWS_S3_CHAT_BUCKET_NAME: ${env:AWS_S3_CHAT_BUCKET_NAME}
    AWS_COGNITO_USER_POOL_ID: ${env:AWS_COGNITO_USER_POOL_ID}
    AWS_COGNITO_USER_POOL_CLIENT_ID: ${env:AWS_COGNITO_USER_POOL_CLIENT_ID}
    VERIFIED_EMAIL_FROM: ${env:VERIFIED_EMAIL_FROM}
    MONDAY_API_KEY: ${env:MONDAY_API_KEY}
    ALFA_BOARD: ${env:ALFA_BOARD}
    BETA_BOARD: ${env:BETA_BOARD}
    DELTA_BOARD: ${env:DELTA_BOARD}
    GEMINI_API_KEY: ${env:GEMINI_API_KEY}
    GOOGLE_SEARCH_API_KEY: ${env:GOOGLE_SEARCH_API_KEY}
    GOOGLE_SEARCH_ENGINE_ID: ${env:GOOGLE_SEARCH_ENGINE_ID}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1
  vpc:
    securityGroupIds:
      - sg-0228a7934137562b2
    subnetIds:
      - subnet-0f5ae3eec18af4eef
      - subnet-04592dbcc1ba4f11e
