"use server";

import { prisma } from "@/db";
import { can } from "@/lib/actions/server-helpers";
import { AppAction } from "../permissions";
import { getAuthenticatedUser } from "../server-utils";

// IdeaStatus is not yet generated by Prisma — define locally until `prisma generate` runs
type IdeaStatus = "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "ARCHIVED" | "IMPLEMENTED";
import { CreateIdeaValues } from "../schemas/basement";
import { revalidatePath } from "next/cache";

// ---------- helpers ----------

function calculateCluster(total: number): { level: number; name: string } {
  if (total <= 10) return { level: 1, name: "EMBRIONÁRIA" };
  if (total <= 15) return { level: 2, name: "EM DESENVOLVIMENTO" };
  if (total <= 20) return { level: 3, name: "MADURA" };
  return { level: 4, name: "PRONTA PARA EXECUÇÃO" };
}

function calculatePriority(total: number): number {
  return Math.round(((total - 5) / 20) * 100);
}

// ---------- queries ----------

export async function getAllIdeas() {
  const ideas = await prisma.inovationIdea.findMany({
    orderBy: { priorityScore: "desc" },
    include: {
      author: {
        include: {
          currentRole: true,
        },
      },
      votes: true,
    },
  });

  return ideas;
}

export async function getMyIdeas() {
  const authUser = await getAuthenticatedUser();
  if (!authUser) return [];

  const ideas = await prisma.inovationIdea.findMany({
    where: { authorId: authUser.id },
    orderBy: { createdAt: "desc" },
    include: {
      author: {
        include: {
          currentRole: true,
        },
      },
      votes: true,
    },
  });

  return ideas;
}

// ---------- mutations ----------

export async function createIdea(data: CreateIdeaValues) {
  const authUser = await getAuthenticatedUser();
  if (!authUser) throw new Error("Unauthorized");

  try {
    const tagsArray = data.tags
      ? data.tags
          .split(",")
          .map((t) => t.trim())
          .filter(Boolean)
      : [];

    const smartTotal =
      data.smartSpecific +
      data.smartMeasurable +
      data.smartAchievable +
      data.smartRelevant +
      data.smartTimeBound;

    const cluster = calculateCluster(smartTotal);
    const priority = calculatePriority(smartTotal);

    await prisma.inovationIdea.create({
      data: {
        title: data.title,
        description: data.description,
        category: data.category,
        ideaType: data.ideaType,
        tags: tagsArray,
        problemDescription: data.problemDescription || null,
        targetAudience: data.targetAudience || null,
        partners: data.partners || null,
        resources: data.resources || [],
        smartSpecific: data.smartSpecific,
        smartMeasurable: data.smartMeasurable,
        smartAchievable: data.smartAchievable,
        smartRelevant: data.smartRelevant,
        smartTimeBound: data.smartTimeBound,
        smartSpecificText: data.smartSpecificText || null,
        smartMeasurableText: data.smartMeasurableText || null,
        smartAchievableText: data.smartAchievableText || null,
        smartRelevantText: data.smartRelevantText || null,
        smartTimeBoundText: data.smartTimeBoundText || null,
        clusterLevel: cluster.level,
        priorityScore: priority,
        authorId: authUser.id,
      },
    });

    revalidatePath("/inovacao/jr-basement");
    return { success: true };
  } catch (error) {
    console.error("Erro ao criar ideia:", error);
    throw new Error("Falha ao criar ideia.");
  }
}

export async function voteForIdea(ideaId: string) {
  const authUser = await getAuthenticatedUser();
  if (!authUser) throw new Error("Unauthorized");

  try {
    const existingVote = await prisma.ideaVote.findUnique({
      where: {
        ideaId_userId: {
          ideaId,
          userId: authUser.id,
        },
      },
    });

    if (existingVote) {
      await prisma.ideaVote.delete({
        where: { id: existingVote.id },
      });
    } else {
      await prisma.ideaVote.create({
        data: {
          ideaId,
          userId: authUser.id,
        },
      });
    }

    revalidatePath("/inovacao/jr-basement");
    return { success: true };
  } catch (error) {
    console.error("Erro ao votar:", error);
    throw new Error("Falha ao registrar voto.");
  }
}

export async function updateIdeaStatus(ideaId: string, status: IdeaStatus) {
  const authUser = await getAuthenticatedUser();
  if (!authUser) throw new Error("Unauthorized");

  const hasPermission = await can(authUser, AppAction.REVIEW_INITIATIVES);
  if (!hasPermission) throw new Error("Sem permissão para alterar status.");

  try {
    await prisma.inovationIdea.update({
      where: { id: ideaId },
      data: { status },
    });

    revalidatePath("/inovacao/jr-basement");
    return { success: true };
  } catch (error) {
    console.error("Erro ao atualizar status:", error);
    throw new Error("Falha ao atualizar status da ideia.");
  }
}

export async function deleteIdea(ideaId: string) {
  const authUser = await getAuthenticatedUser();
  if (!authUser) throw new Error("Unauthorized");

  const idea = await prisma.inovationIdea.findUnique({
    where: { id: ideaId },
  });

  if (!idea) throw new Error("Ideia não encontrada.");

  const isAuthor = idea.authorId === authUser.id;
  const isManager = await can(authUser, AppAction.REVIEW_INITIATIVES);

  if (!isAuthor && !isManager) {
    throw new Error("Sem permissão para deletar esta ideia.");
  }

  try {
    await prisma.inovationIdea.delete({
      where: { id: ideaId },
    });

    revalidatePath("/inovacao/jr-basement");
    return { success: true };
  } catch (error) {
    console.error("Erro ao deletar ideia:", error);
    throw new Error("Falha ao deletar ideia.");
  }
}
