-- CreateEnum
CREATE TYPE "LinkAreas" AS ENUM ('GERAL', 'CONSULTORIA', 'TATICO', 'PRESIDENCIA', 'OPERACOES', 'PESSOAS', 'PROJETOS', 'MERCADO');

-- AlterTable
ALTER TABLE "UsefulLink" ADD COLUMN     "area" "LinkAreas" NOT NULL DEFAULT 'GERAL',
ADD COLUMN     "isGlobal" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "userId" DROP NOT NULL;
