"use client";

import { useState, useMemo } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Badge } from "@/components/ui/badge";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";
import {
  Zap,
  Plus,
  Search,
  Rocket,
  FlaskConical,
  Lightbulb,
  BarChart3,
  Trash2,
  Crown,
  Medal,
  Trophy,
  X,
  SlidersHorizontal,
  Sparkles,
  Shield,
  ArrowRight,
} from "lucide-react";
import {
  getAllIdeas,
  getMyIdeas,
  voteForIdea,
  updateIdeaStatus,
  deleteIdea,
} from "@/lib/actions/basement";
import { useAuth } from "@/lib/auth/AuthProvider";
import { useAllowedActions } from "@/lib/auth/AllowedActionsProvider";
import { AppAction } from "@/lib/permissions";
import Pagination from "@/app/_components/Global/Custom/Pagination";

// IdeaStatus is not yet generated by Prisma — define locally until `prisma generate` runs
type IdeaStatus = "DRAFT" | "SUBMITTED" | "UNDER_REVIEW" | "ARCHIVED" | "IMPLEMENTED";
import ModalConfirm from "@/app/_components/Global/ModalConfirm";
import IdeaCard from "./IdeaCard";
import CreateIdeaWizard from "./CreateIdeaWizard";
import { formatDistanceToNow } from "date-fns";
import { ptBR } from "date-fns/locale";

// ---------- types ----------

export type IdeaWithRelations = {
  id: string;
  title: string;
  description: string;
  category: string;
  status: string;
  ideaType: string;
  authorId: string;
  tags: string[];
  problemDescription: string | null;
  targetAudience: string | null;
  partners: string | null;
  resources: string[];
  smartSpecific: number;
  smartMeasurable: number;
  smartAchievable: number;
  smartRelevant: number;
  smartTimeBound: number;
  smartSpecificText: string | null;
  smartMeasurableText: string | null;
  smartAchievableText: string | null;
  smartRelevantText: string | null;
  smartTimeBoundText: string | null;
  clusterLevel: number;
  priorityScore: number;
  implementedAsId: string | null;
  createdAt: Date;
  updatedAt: Date;
  author: {
    id: string;
    name: string;
    currentRole: { id: string; name: string; description: string } | null;
    [key: string]: unknown;
  };
  votes: { id: string; ideaId: string; userId: string; createdAt: Date }[];
};

// ---------- constants ----------

const ITEMS_PER_PAGE = 9;

const STATUS_LABELS: Record<string, string> = {
  DRAFT: "Rascunho",
  SUBMITTED: "Submetida",
  UNDER_REVIEW: "Em Revisao",
  ARCHIVED: "Arquivada",
  IMPLEMENTED: "Implementada",
};

const STATUS_OPTIONS = Object.entries(STATUS_LABELS).map(([value, label]) => ({
  value,
  label,
}));

const CATEGORY_OPTIONS = [
  { value: "ALL", label: "Todas" },
  { value: "PROCESSO", label: "Processo" },
  { value: "PRODUTO", label: "Produto" },
  { value: "TECNOLOGIA", label: "Tecnologia" },
  { value: "CULTURA", label: "Cultura" },
  { value: "OUTRO", label: "Outro" },
];

const SORT_OPTIONS = [
  { value: "votes", label: "Mais votadas" },
  { value: "recent", label: "Mais recentes" },
  { value: "priority", label: "Maior prioridade" },
];

const CLUSTER_STYLES: Record<number, { bg: string; border: string; text: string; label: string; color: string }> = {
  1: { bg: "bg-red-500/20", border: "border-red-500/50", text: "text-red-400", label: "Embrionaria", color: "#ef4444" },
  2: { bg: "bg-orange-500/20", border: "border-orange-500/50", text: "text-orange-400", label: "Em Desenvolvimento", color: "#f97316" },
  3: { bg: "bg-blue-500/20", border: "border-blue-500/50", text: "text-blue-400", label: "Madura", color: "#3b82f6" },
  4: { bg: "bg-[#f5b719]/20", border: "border-[#f5b719]/50", text: "text-[#f5b719]", label: "Pronta para Execucao", color: "#f5b719" },
};

const SMART_DISPLAY = [
  { letter: "S", label: "Especifica", color: "#0126fb", key: "smartSpecific" as const },
  { letter: "M", label: "Mensuravel", color: "#22c55e", key: "smartMeasurable" as const },
  { letter: "A", label: "Atingivel", color: "#f59e0b", key: "smartAchievable" as const },
  { letter: "R", label: "Relevante", color: "#ef4444", key: "smartRelevant" as const },
  { letter: "T", label: "Temporal", color: "#8b5cf6", key: "smartTimeBound" as const },
];

// ---------- helpers ----------

function SmartCircle({ value, color, letter, label }: { value: number; color: string; letter: string; label: string }) {
  const pct = (value / 5) * 100;
  const radius = 28;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (pct / 100) * circumference;

  return (
    <div className="flex flex-col items-center gap-2">
      <div className="relative w-[72px] h-[72px]">
        <svg className="w-full h-full -rotate-90" viewBox="0 0 64 64">
          <circle cx="32" cy="32" r={radius} fill="none" stroke="white" strokeOpacity="0.08" strokeWidth="4" />
          <circle
            cx="32"
            cy="32"
            r={radius}
            fill="none"
            stroke={color}
            strokeWidth="4"
            strokeLinecap="round"
            strokeDasharray={circumference}
            strokeDashoffset={offset}
            className="transition-all duration-700"
          />
        </svg>
        <div className="absolute inset-0 flex flex-col items-center justify-center">
          <span className="text-lg font-bold text-white">{value}</span>
          <span className="text-[10px] font-bold" style={{ color }}>{letter}</span>
        </div>
      </div>
      <span className="text-[10px] text-gray-500 text-center leading-tight">{label}</span>
    </div>
  );
}

function PriorityCircle({ value }: { value: number }) {
  const radius = 42;
  const circumference = 2 * Math.PI * radius;
  const offset = circumference - (value / 100) * circumference;
  const gradientId = "priority-gradient";

  return (
    <div className="relative w-[110px] h-[110px]">
      <svg className="w-full h-full -rotate-90" viewBox="0 0 96 96">
        <defs>
          <linearGradient id={gradientId} x1="0%" y1="0%" x2="100%" y2="0%">
            <stop offset="0%" stopColor="#0126fb" />
            <stop offset="100%" stopColor="#f5b719" />
          </linearGradient>
        </defs>
        <circle cx="48" cy="48" r={radius} fill="none" stroke="white" strokeOpacity="0.06" strokeWidth="6" />
        <circle
          cx="48"
          cy="48"
          r={radius}
          fill="none"
          stroke={`url(#${gradientId})`}
          strokeWidth="6"
          strokeLinecap="round"
          strokeDasharray={circumference}
          strokeDashoffset={offset}
          className="transition-all duration-700"
        />
      </svg>
      <div className="absolute inset-0 flex flex-col items-center justify-center">
        <span className="text-2xl font-bold text-[#f5b719]">{value}%</span>
        <span className="text-[10px] text-gray-500 uppercase tracking-wider">Prioridade</span>
      </div>
    </div>
  );
}

// ---------- component ----------

interface BasementContentProps {
  initialAllIdeas: IdeaWithRelations[];
  initialMyIdeas: IdeaWithRelations[];
}

export default function BasementContent({ initialAllIdeas, initialMyIdeas }: BasementContentProps) {
  const { user } = useAuth();
  const { canDo } = useAllowedActions();
  const queryClient = useQueryClient();

  // State
  const [wizardOpen, setWizardOpen] = useState(false);
  const [selectedIdea, setSelectedIdea] = useState<IdeaWithRelations | null>(null);
  const [deleteTarget, setDeleteTarget] = useState<string | null>(null);
  const [page, setPage] = useState(1);
  const [myPage, setMyPage] = useState(1);

  // Filters
  const [search, setSearch] = useState("");
  const [categoryFilter, setCategoryFilter] = useState("ALL");
  const [statusFilter, setStatusFilter] = useState("ALL");
  const [sortBy, setSortBy] = useState("priority");

  // Queries
  const { data: allIdeas = initialAllIdeas } = useQuery({
    queryKey: ["basement-ideas"],
    queryFn: getAllIdeas,
    initialData: initialAllIdeas,
  });

  const { data: myIdeas = initialMyIdeas } = useQuery({
    queryKey: ["basement-my-ideas"],
    queryFn: getMyIdeas,
    initialData: initialMyIdeas,
  });

  // Mutations
  const voteMutation = useMutation({
    mutationFn: voteForIdea,
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["basement-ideas"] });
      queryClient.invalidateQueries({ queryKey: ["basement-my-ideas"] });
    },
    onError: () => toast.error("Erro ao votar."),
  });

  const statusMutation = useMutation({
    mutationFn: ({ ideaId, status }: { ideaId: string; status: IdeaStatus }) =>
      updateIdeaStatus(ideaId, status),
    onSuccess: () => {
      toast.success("Status atualizado!");
      queryClient.invalidateQueries({ queryKey: ["basement-ideas"] });
      setSelectedIdea(null);
    },
    onError: () => toast.error("Erro ao atualizar status."),
  });

  const deleteMutation = useMutation({
    mutationFn: deleteIdea,
    onSuccess: () => {
      toast.success("Ideia excluida!");
      queryClient.invalidateQueries({ queryKey: ["basement-ideas"] });
      queryClient.invalidateQueries({ queryKey: ["basement-my-ideas"] });
      setDeleteTarget(null);
    },
    onError: () => toast.error("Erro ao excluir ideia."),
  });

  // Ranked ideas (by votes) -- used for ranking badges and podium
  const rankedIdeas = useMemo(() => {
    return [...allIdeas].sort((a, b) => b.votes.length - a.votes.length);
  }, [allIdeas]);

  const rankMap = useMemo(() => {
    const map = new Map<string, number>();
    rankedIdeas.forEach((idea, i) => {
      if (idea.votes.length > 0) {
        map.set(idea.id, i + 1);
      }
    });
    return map;
  }, [rankedIdeas]);

  // Top 3 for podium
  const top3Ideas = useMemo(() => {
    return rankedIdeas.filter((i) => i.votes.length > 0).slice(0, 3);
  }, [rankedIdeas]);

  // Filtered + sorted ideas
  const filteredIdeas = useMemo(() => {
    let result = [...allIdeas];

    if (search) {
      const q = search.toLowerCase();
      result = result.filter(
        (i) =>
          i.title.toLowerCase().includes(q) ||
          i.tags.some((t: string) => t.toLowerCase().includes(q))
      );
    }

    if (categoryFilter !== "ALL") {
      result = result.filter((i) => i.category === categoryFilter);
    }

    if (statusFilter !== "ALL") {
      result = result.filter((i) => i.status === statusFilter);
    }

    switch (sortBy) {
      case "votes":
        result.sort((a, b) => b.votes.length - a.votes.length);
        break;
      case "recent":
        result.sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
        break;
      case "priority":
      default:
        result.sort((a, b) => b.priorityScore - a.priorityScore);
        break;
    }

    return result;
  }, [allIdeas, search, categoryFilter, statusFilter, sortBy]);

  const hasActiveFilters = search !== "" || categoryFilter !== "ALL" || statusFilter !== "ALL";

  const clearFilters = () => {
    setSearch("");
    setCategoryFilter("ALL");
    setStatusFilter("ALL");
    setSortBy("priority");
    setPage(1);
  };

  // Pagination
  const totalPages = Math.max(1, Math.ceil(filteredIdeas.length / ITEMS_PER_PAGE));
  const paginatedIdeas = filteredIdeas.slice((page - 1) * ITEMS_PER_PAGE, page * ITEMS_PER_PAGE);
  const showingFrom = filteredIdeas.length > 0 ? (page - 1) * ITEMS_PER_PAGE + 1 : 0;
  const showingTo = Math.min(page * ITEMS_PER_PAGE, filteredIdeas.length);

  const myTotalPages = Math.max(1, Math.ceil(myIdeas.length / ITEMS_PER_PAGE));
  const paginatedMyIdeas = myIdeas.slice((myPage - 1) * ITEMS_PER_PAGE, myPage * ITEMS_PER_PAGE);

  // Stats
  const totalIdeasCount = allIdeas.length;
  const readyForExecution = allIdeas.filter((i: IdeaWithRelations) => i.clusterLevel === 4).length;
  const inDevelopment = allIdeas.filter((i: IdeaWithRelations) => i.clusterLevel >= 2 && i.clusterLevel <= 3).length;
  const myIdeasCount = myIdeas.length;

  // SMART values for the detail modal
  const getSmartValues = (idea: IdeaWithRelations) => [
    idea.smartSpecific,
    idea.smartMeasurable,
    idea.smartAchievable,
    idea.smartRelevant,
    idea.smartTimeBound,
  ];

  // ---------- podium medal colors ----------
  const podiumConfig = [
    { border: "border-[#f5b719]", glow: "shadow-[0_0_30px_rgba(245,183,25,0.15)]", icon: Crown, iconColor: "text-[#f5b719]", label: "1o Lugar", bg: "bg-[#f5b719]/5" },
    { border: "border-gray-400", glow: "shadow-[0_0_20px_rgba(156,163,175,0.1)]", icon: Medal, iconColor: "text-gray-400", label: "2o Lugar", bg: "bg-gray-400/5" },
    { border: "border-amber-700", glow: "shadow-[0_0_20px_rgba(180,83,9,0.1)]", icon: Trophy, iconColor: "text-amber-700", label: "3o Lugar", bg: "bg-amber-700/5" },
  ];

  return (
    <div className="min-h-screen space-y-8 p-4 md:p-6 lg:p-8">

      {/* ====== HERO HEADER ====== */}
      <div className="relative overflow-hidden rounded-2xl border border-[#0126fb]/20 bg-gradient-to-br from-[#010d26] via-[#00205e]/40 to-[#010d26] p-8 md:p-10">
        {/* Background grid overlay */}
        <div
          className="pointer-events-none absolute inset-0 opacity-[0.03]"
          style={{
            backgroundImage: "linear-gradient(rgba(255,255,255,.1) 1px, transparent 1px), linear-gradient(90deg, rgba(255,255,255,.1) 1px, transparent 1px)",
            backgroundSize: "40px 40px",
          }}
        />
        {/* Glow orb behind icon */}
        <div className="absolute -top-20 -left-20 w-60 h-60 rounded-full bg-[#f5b719]/10 blur-[100px]" />
        <div className="absolute -bottom-20 -right-20 w-60 h-60 rounded-full bg-[#0126fb]/10 blur-[100px]" />

        <div className="relative flex flex-col md:flex-row md:items-center justify-between gap-6">
          <div className="flex items-center gap-4">
            {/* Lightning icon with animated glow */}
            <div className="relative flex-shrink-0">
              <div className="absolute inset-0 bg-[#f5b719]/20 blur-2xl rounded-full animate-pulse" />
              <div className="relative w-14 h-14 md:w-16 md:h-16 rounded-2xl bg-gradient-to-br from-[#f5b719]/20 to-[#f5b719]/5 border border-[#f5b719]/30 flex items-center justify-center">
                <Zap className="w-7 h-7 md:w-8 md:h-8 text-[#f5b719] drop-shadow-[0_0_12px_rgba(245,183,25,0.6)]" />
              </div>
            </div>
            <div>
              <h1 className="text-3xl md:text-4xl lg:text-5xl font-extrabold text-white tracking-tight">
                JR BASEMENT
              </h1>
              <p className="text-gray-400 text-sm md:text-base mt-1 max-w-lg">
                Transforme sua ideia em impacto. Registre, estruture e veja sua proposta ser avaliada.
              </p>
            </div>
          </div>

          <Button
            onClick={() => setWizardOpen(true)}
            className="group relative overflow-hidden bg-gradient-to-r from-[#f5b719] to-[#f59e0b] text-[#010d26] font-bold text-sm px-6 py-3 h-auto rounded-xl hover:shadow-[0_0_25px_rgba(245,183,25,0.3)] transition-all duration-300 hover:scale-105"
          >
            <div className="absolute inset-0 bg-white/10 opacity-0 group-hover:opacity-100 transition-opacity" />
            <Zap className="w-4 h-4 mr-2" />
            Nova Ideia
          </Button>
        </div>
      </div>

      {/* ====== STATS CARDS ====== */}
      <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 md:gap-5">
        {[
          {
            label: "TOTAL IDEIAS",
            value: totalIdeasCount,
            icon: Lightbulb,
            gradient: "from-[#010d26]/90 to-[#010d26]",
            iconBg: "bg-[#0126fb]/15",
            iconColor: "text-[#0126fb]",
            glowColor: "shadow-[0_0_20px_rgba(1,38,251,0.08)]",
          },
          {
            label: "PRONTAS P/ EXECUCAO",
            value: readyForExecution,
            icon: Rocket,
            gradient: "from-[#010d26]/90 to-[#010d26]",
            iconBg: "bg-[#f5b719]/15",
            iconColor: "text-[#f5b719]",
            glowColor: "shadow-[0_0_20px_rgba(245,183,25,0.08)]",
          },
          {
            label: "EM DESENVOLVIMENTO",
            value: inDevelopment,
            icon: FlaskConical,
            gradient: "from-[#010d26]/90 to-[#010d26]",
            iconBg: "bg-orange-500/15",
            iconColor: "text-orange-400",
            glowColor: "shadow-[0_0_20px_rgba(249,115,22,0.08)]",
          },
          {
            label: "MINHAS IDEIAS",
            value: myIdeasCount,
            icon: BarChart3,
            gradient: "from-[#010d26]/90 to-[#010d26]",
            iconBg: "bg-green-500/15",
            iconColor: "text-green-400",
            glowColor: "shadow-[0_0_20px_rgba(34,197,94,0.08)]",
          },
        ].map((stat) => (
          <div
            key={stat.label}
            className={cn(
              "group relative bg-gradient-to-br rounded-2xl p-5 md:p-6 border border-[#0126fb]/10 hover:border-[#0126fb]/25 transition-all duration-300 hover:scale-[1.02]",
              stat.gradient,
              stat.glowColor
            )}
          >
            <div className={cn("w-11 h-11 rounded-xl flex items-center justify-center mb-4", stat.iconBg)}>
              <stat.icon className={cn("w-5 h-5", stat.iconColor)} />
            </div>
            <p className="text-3xl md:text-4xl font-bold text-white tracking-tight">{stat.value}</p>
            <p className="text-[10px] md:text-xs text-gray-500 uppercase tracking-[0.15em] mt-1 font-medium">{stat.label}</p>
          </div>
        ))}
      </div>

      {/* ====== RANKING PODIUM ====== */}
      {top3Ideas.length > 0 && (
        <div className="space-y-4">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-[#f5b719]/15 flex items-center justify-center">
              <Trophy className="w-4 h-4 text-[#f5b719]" />
            </div>
            <div>
              <h2 className="text-lg font-bold text-white">Ideias em Destaque</h2>
              <p className="text-xs text-gray-500">As ideias mais votadas da plataforma</p>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
            {top3Ideas.map((idea, index) => {
              const config = podiumConfig[index];
              const cluster = CLUSTER_STYLES[idea.clusterLevel] || CLUSTER_STYLES[1];
              return (
                <button
                  key={idea.id}
                  onClick={() => setSelectedIdea(idea)}
                  className={cn(
                    "group relative text-left rounded-2xl border-2 p-5 transition-all duration-300 hover:scale-[1.02] cursor-pointer",
                    config.border,
                    config.glow,
                    config.bg
                  )}
                >
                  {/* Position badge */}
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <config.icon className={cn("w-5 h-5", config.iconColor)} />
                      <span className={cn("text-xs font-bold uppercase tracking-wider", config.iconColor)}>
                        {config.label}
                      </span>
                    </div>
                    <div className="flex items-center gap-1 text-[#f5b719]">
                      <Zap className="w-3.5 h-3.5 fill-[#f5b719]" />
                      <span className="text-sm font-bold">{idea.votes.length}</span>
                    </div>
                  </div>

                  <h3 className="text-white font-bold text-base line-clamp-2 mb-2 group-hover:text-[#f5b719] transition-colors">
                    {idea.title}
                  </h3>

                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <div className="w-6 h-6 rounded-full bg-[#0126fb]/30 flex items-center justify-center text-[10px] text-white font-bold uppercase">
                        {idea.author.name?.charAt(0) || "?"}
                      </div>
                      <span className="text-xs text-gray-400 truncate max-w-[120px]">{idea.author.name}</span>
                    </div>
                    <Badge className={cn("text-[10px] border", cluster.bg, cluster.border, cluster.text)}>
                      {cluster.label}
                    </Badge>
                  </div>
                </button>
              );
            })}
          </div>
        </div>
      )}

      {/* ====== TABS ====== */}
      <Tabs defaultValue="gallery" className="space-y-5">
        <TabsList className="bg-[#010d26]/80 border border-[#0126fb]/15 rounded-xl p-1 h-auto">
          <TabsTrigger
            value="gallery"
            className="rounded-lg px-5 py-2.5 text-sm font-medium data-[state=active]:bg-[#0126fb] data-[state=active]:text-white data-[state=active]:shadow-lg data-[state=active]:shadow-[#0126fb]/20 text-gray-400 transition-all duration-200"
          >
            Galeria de Ideias
            <span className="ml-2 text-[10px] px-1.5 py-0.5 rounded-full bg-white/10 font-bold">
              {allIdeas.length}
            </span>
          </TabsTrigger>
          <TabsTrigger
            value="mine"
            className="rounded-lg px-5 py-2.5 text-sm font-medium data-[state=active]:bg-[#0126fb] data-[state=active]:text-white data-[state=active]:shadow-lg data-[state=active]:shadow-[#0126fb]/20 text-gray-400 transition-all duration-200"
          >
            Minhas Ideias
            <span className="ml-2 text-[10px] px-1.5 py-0.5 rounded-full bg-white/10 font-bold">
              {myIdeas.length}
            </span>
          </TabsTrigger>
        </TabsList>

        {/* ====== GALLERY TAB ====== */}
        <TabsContent value="gallery" className="space-y-5">

          {/* Filters bar */}
          <div className="flex flex-wrap items-center gap-3 p-4 rounded-xl bg-white/[0.02] border border-[#0126fb]/10">
            {/* Search */}
            <div className="relative flex-1 min-w-[220px]">
              <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
              <Input
                placeholder="Buscar por titulo ou tag..."
                value={search}
                onChange={(e) => {
                  setSearch(e.target.value);
                  setPage(1);
                }}
                className="pl-10 bg-white/5 border-white/10 text-white rounded-full h-10 placeholder:text-gray-600 focus-visible:ring-[#0126fb]/40 focus-visible:border-[#0126fb]/40"
              />
            </div>

            {/* Category pills */}
            <div className="flex flex-wrap gap-1.5">
              {CATEGORY_OPTIONS.map((opt) => (
                <button
                  key={opt.value}
                  onClick={() => {
                    setCategoryFilter(opt.value);
                    setPage(1);
                  }}
                  className={cn(
                    "px-3 py-1.5 rounded-full text-xs font-medium transition-all duration-200 border",
                    categoryFilter === opt.value
                      ? "bg-[#0126fb] text-white border-[#0126fb] shadow-md shadow-[#0126fb]/20"
                      : "bg-transparent text-gray-400 border-white/10 hover:border-[#0126fb]/40 hover:text-gray-300"
                  )}
                >
                  {opt.label}
                </button>
              ))}
            </div>

            {/* Status select */}
            <Select value={statusFilter} onValueChange={(v) => { setStatusFilter(v); setPage(1); }}>
              <SelectTrigger className="w-[150px] bg-white/5 border-white/10 text-white rounded-full h-10 text-xs">
                <SlidersHorizontal className="w-3.5 h-3.5 mr-1.5 text-gray-500" />
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent className="bg-[#010d26] border-white/10">
                <SelectItem value="ALL" className="text-white hover:bg-white/10">Todos os Status</SelectItem>
                {STATUS_OPTIONS.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value} className="text-white hover:bg-white/10">
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            {/* Sort select */}
            <Select value={sortBy} onValueChange={setSortBy}>
              <SelectTrigger className="w-[160px] bg-white/5 border-white/10 text-white rounded-full h-10 text-xs">
                <SelectValue placeholder="Ordenar" />
              </SelectTrigger>
              <SelectContent className="bg-[#010d26] border-white/10">
                {SORT_OPTIONS.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value} className="text-white hover:bg-white/10">
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            {/* Clear filters */}
            {hasActiveFilters && (
              <button
                onClick={clearFilters}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs text-red-400 hover:text-red-300 border border-red-500/20 hover:border-red-500/40 transition-all"
              >
                <X className="w-3 h-3" />
                Limpar filtros
              </button>
            )}
          </div>

          {/* Ideas Grid */}
          {paginatedIdeas.length > 0 ? (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                {paginatedIdeas.map((idea) => (
                  <IdeaCard
                    key={idea.id}
                    idea={idea}
                    rank={rankMap.get(idea.id)}
                    onVote={(id) => voteMutation.mutate(id)}
                    onSelect={setSelectedIdea}
                    onDelete={(id) => setDeleteTarget(id)}
                    isVoting={voteMutation.isPending}
                  />
                ))}
              </div>

              {/* Pagination info + controls */}
              <div className="flex flex-col sm:flex-row items-center justify-between gap-3 pt-2">
                <p className="text-xs text-gray-500">
                  Mostrando <span className="text-gray-300 font-medium">{showingFrom}-{showingTo}</span> de{" "}
                  <span className="text-gray-300 font-medium">{filteredIdeas.length}</span> ideias
                </p>
                {totalPages > 1 && (
                  <Pagination currentPage={page} totalPages={totalPages} onPageChange={setPage} />
                )}
              </div>
            </>
          ) : (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <div className="w-20 h-20 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-center mb-5">
                <Sparkles className="w-9 h-9 text-gray-600" />
              </div>
              <p className="text-gray-400 font-medium text-base">Nenhuma ideia encontrada</p>
              <p className="text-gray-600 text-sm mt-1.5 max-w-xs">
                {hasActiveFilters
                  ? "Tente ajustar os filtros para encontrar o que procura."
                  : "Seja o primeiro a contribuir e lance uma ideia!"}
              </p>
              {hasActiveFilters && (
                <button
                  onClick={clearFilters}
                  className="mt-4 text-xs text-[#0126fb] hover:text-[#0126fb]/80 underline underline-offset-2"
                >
                  Limpar todos os filtros
                </button>
              )}
            </div>
          )}
        </TabsContent>

        {/* ====== MY IDEAS TAB ====== */}
        <TabsContent value="mine" className="space-y-5">
                    {/* Filters bar */}
          <div className="flex flex-wrap items-center gap-3 p-4 rounded-xl bg-white/[0.02] border border-[#0126fb]/10">
            {/* Search */}
            <div className="relative flex-1 min-w-[220px]">
              <Search className="absolute left-3.5 top-1/2 -translate-y-1/2 w-4 h-4 text-gray-500" />
              <Input
                placeholder="Buscar por titulo ou tag..."
                value={search}
                onChange={(e) => {
                  setSearch(e.target.value);
                  setPage(1);
                }}
                className="pl-10 bg-white/5 border-white/10 text-white rounded-full h-10 placeholder:text-gray-600 focus-visible:ring-[#0126fb]/40 focus-visible:border-[#0126fb]/40"
              />
            </div>

            {/* Category pills */}
            <div className="flex flex-wrap gap-1.5">
              {CATEGORY_OPTIONS.map((opt) => (
                <button
                  key={opt.value}
                  onClick={() => {
                    setCategoryFilter(opt.value);
                    setPage(1);
                  }}
                  className={cn(
                    "px-3 py-1.5 rounded-full text-xs font-medium transition-all duration-200 border",
                    categoryFilter === opt.value
                      ? "bg-[#0126fb] text-white border-[#0126fb] shadow-md shadow-[#0126fb]/20"
                      : "bg-transparent text-gray-400 border-white/10 hover:border-[#0126fb]/40 hover:text-gray-300"
                  )}
                >
                  {opt.label}
                </button>
              ))}
            </div>

            {/* Status select */}
            <Select value={statusFilter} onValueChange={(v) => { setStatusFilter(v); setPage(1); }}>
              <SelectTrigger className="w-[150px] bg-white/5 border-white/10 text-white rounded-full h-10 text-xs">
                <SlidersHorizontal className="w-3.5 h-3.5 mr-1.5 text-gray-500" />
                <SelectValue placeholder="Status" />
              </SelectTrigger>
              <SelectContent className="bg-[#010d26] border-white/10">
                <SelectItem value="ALL" className="text-white hover:bg-white/10">Todos os Status</SelectItem>
                {STATUS_OPTIONS.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value} className="text-white hover:bg-white/10">
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            {/* Sort select */}
            <Select value={sortBy} onValueChange={setSortBy}>
              <SelectTrigger className="w-[160px] bg-white/5 border-white/10 text-white rounded-full h-10 text-xs">
                <SelectValue placeholder="Ordenar" />
              </SelectTrigger>
              <SelectContent className="bg-[#010d26] border-white/10">
                {SORT_OPTIONS.map((opt) => (
                  <SelectItem key={opt.value} value={opt.value} className="text-white hover:bg-white/10">
                    {opt.label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>

            {/* Clear filters */}
            {hasActiveFilters && (
              <button
                onClick={clearFilters}
                className="flex items-center gap-1.5 px-3 py-1.5 rounded-full text-xs text-red-400 hover:text-red-300 border border-red-500/20 hover:border-red-500/40 transition-all"
              >
                <X className="w-3 h-3" />
                Limpar filtros
              </button>
            )}
          </div>

          {paginatedMyIdeas.length > 0 ? (
            <>
              <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-6">
                {paginatedMyIdeas.map((idea: IdeaWithRelations) => (
                  <IdeaCard
                    key={idea.id}
                    idea={idea}
                    rank={rankMap.get(idea.id)}
                    onVote={(id) => voteMutation.mutate(id)}
                    onSelect={setSelectedIdea}
                    onDelete={(id) => setDeleteTarget(id)}
                    isVoting={voteMutation.isPending}
                  />
                ))}
              </div>

              {myTotalPages > 1 && (
                <div className="flex justify-end pt-2">
                  <Pagination currentPage={myPage} totalPages={myTotalPages} onPageChange={setMyPage} />
                </div>
              )}
            </>
          ) : (
            <div className="flex flex-col items-center justify-center py-20 text-center">
              <div className="w-20 h-20 rounded-2xl bg-white/[0.03] border border-white/10 flex items-center justify-center mb-5">
                <Lightbulb className="w-9 h-9 text-gray-600" />
              </div>
              <p className="text-gray-400 font-medium text-base">Voce ainda nao submeteu nenhuma ideia</p>
              <p className="text-gray-600 text-sm mt-1.5 max-w-xs">
                Crie sua primeira ideia e comece a transformar o ambiente!
              </p>
              <Button
                onClick={() => setWizardOpen(true)}
                className="mt-5 bg-gradient-to-r from-[#0126fb] to-[#0126fb]/80 text-white font-medium gap-2 rounded-xl hover:shadow-lg hover:shadow-[#0126fb]/20 transition-all"
              >
                <Plus className="w-4 h-4" />
                Criar minha primeira ideia
              </Button>
            </div>
          )}
        </TabsContent>
      </Tabs>

      {/* ====== WIZARD ====== */}
      <CreateIdeaWizard open={wizardOpen} onOpenChange={setWizardOpen} />

      {/* ====== DELETE CONFIRM ====== */}
      {deleteTarget && (
        <ModalConfirm
          open={!!deleteTarget}
          onCancel={() => setDeleteTarget(null)}
          onConfirm={() => deleteMutation.mutate(deleteTarget)}
          title="Excluir Ideia"
          description="Tem certeza que deseja excluir esta ideia? Esta acao nao pode ser desfeita."
          confirmText="Excluir"
          cancelText="Cancelar"
          isLoading={deleteMutation.isPending}
        />
      )}

      {/* ====== DETAIL MODAL ====== */}
      {selectedIdea && (() => {
        // Keep modal in sync with query data so votes/status update in real-time
        const liveIdea = allIdeas.find((i) => i.id === selectedIdea.id) || selectedIdea;

        return (
        <Dialog open={!!selectedIdea} onOpenChange={() => setSelectedIdea(null)}>
          <DialogContent
            showCloseButton={false}
            className="sm:max-w-2xl md:max-w-3xl max-h-[90vh] bg-[#010d26] border-[#0126fb]/20 text-white p-0 gap-0 overflow-hidden flex flex-col"
          >
            {/* Modal header with colored left border */}
            <div
              className="relative p-6 md:p-8 pb-4 border-b border-white/5 flex-shrink-0"
              style={{ borderLeft: `4px solid ${CLUSTER_STYLES[liveIdea.clusterLevel]?.color || '#0126fb'}` }}
            >
              <button
                onClick={() => setSelectedIdea(null)}
                className="absolute top-4 right-4 w-8 h-8 rounded-lg bg-white/5 flex items-center justify-center text-gray-400 hover:text-white hover:bg-white/10 transition-all z-10"
              >
                <X className="w-4 h-4" />
              </button>

              <DialogHeader className="text-left">
                <DialogTitle className="text-xl md:text-2xl font-bold text-white pr-10 leading-tight">
                  {liveIdea.title}
                </DialogTitle>
              </DialogHeader>

              {/* Badges row */}
              <div className="flex flex-wrap gap-2 mt-4">
                <Badge variant="outline" className="border-[#0126fb]/40 text-[#0126fb] bg-[#0126fb]/10 text-xs">
                  {liveIdea.category}
                </Badge>
                <Badge
                  className={cn(
                    "border text-xs",
                    CLUSTER_STYLES[liveIdea.clusterLevel]?.bg,
                    CLUSTER_STYLES[liveIdea.clusterLevel]?.border,
                    CLUSTER_STYLES[liveIdea.clusterLevel]?.text
                  )}
                >
                  {CLUSTER_STYLES[liveIdea.clusterLevel]?.label}
                </Badge>
                <Badge variant="outline" className="border-white/15 text-gray-400 text-xs">
                  {STATUS_LABELS[liveIdea.status]}
                </Badge>
                <Badge variant="outline" className="border-white/15 text-gray-400 text-xs">
                  {liveIdea.ideaType === "INTERNAL" ? "Interna" : "Externa"}
                </Badge>
              </div>
            </div>

            {/* Modal body - scrollable */}
            <div className="flex-1 overflow-y-auto p-6 md:p-8 space-y-6 scrollbar-thin scrollbar-thumb-gray-700 scrollbar-track-transparent">

              {/* SMART Scores - circular indicators */}
              <div>
                <p className="text-[10px] text-gray-500 uppercase tracking-[0.2em] font-semibold mb-4">
                  Scores SMART
                </p>
                <div className="flex flex-wrap items-center justify-center gap-4 md:gap-6 p-5 rounded-xl bg-white/[0.02] border border-white/5">
                  {SMART_DISPLAY.map((s, i) => {
                    const values = getSmartValues(liveIdea);
                    return (
                      <SmartCircle
                        key={s.letter}
                        value={values[i]}
                        color={s.color}
                        letter={s.letter}
                        label={s.label}
                      />
                    );
                  })}
                </div>
              </div>

              {/* Priority + Total Score */}
              <div className="flex items-center gap-6 p-5 rounded-xl bg-white/[0.02] border border-white/5">
                <PriorityCircle value={liveIdea.priorityScore} />
                <div className="flex-1 space-y-3">
                  <div>
                    <p className="text-[10px] text-gray-500 uppercase tracking-[0.15em]">Score Total SMART</p>
                    <p className="text-white font-bold text-2xl">
                      {getSmartValues(liveIdea).reduce((a, b) => a + b, 0)}
                      <span className="text-gray-500 text-sm font-normal">/25</span>
                    </p>
                  </div>
                  <div className="w-full h-2 bg-white/5 rounded-full overflow-hidden">
                    <div
                      className="h-full bg-gradient-to-r from-[#0126fb] to-[#f5b719] rounded-full transition-all duration-500"
                      style={{ width: `${(getSmartValues(liveIdea).reduce((a, b) => a + b, 0) / 25) * 100}%` }}
                    />
                  </div>
                </div>
              </div>

              {/* Description */}
              <div>
                <p className="text-[10px] text-gray-500 uppercase tracking-[0.2em] font-semibold mb-2">Descricao</p>
                <div className="h-px bg-white/5 mb-3" />
                <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{liveIdea.description}</p>
              </div>

              {/* Problem */}
              {liveIdea.problemDescription && (
                <div>
                  <p className="text-[10px] text-gray-500 uppercase tracking-[0.2em] font-semibold mb-2">Problema / Oportunidade</p>
                  <div className="h-px bg-white/5 mb-3" />
                  <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{liveIdea.problemDescription}</p>
                </div>
              )}

              {/* SMART Texts */}
              {SMART_DISPLAY.map((s) => {
                const textKey = `${s.key}Text` as keyof IdeaWithRelations;
                const textValue = liveIdea[textKey];
                if (!textValue) return null;
                return (
                  <div key={s.key}>
                    <p className="text-[10px] text-gray-500 uppercase tracking-[0.2em] font-semibold mb-2">
                      <span style={{ color: s.color }}>{s.letter}</span> - {s.label}
                    </p>
                    <div className="h-px bg-white/5 mb-3" />
                    <p className="text-gray-300 text-sm leading-relaxed whitespace-pre-wrap">{String(textValue)}</p>
                  </div>
                );
              })}

              {/* Resources */}
              {liveIdea.resources.length > 0 && (
                <div>
                  <p className="text-[10px] text-gray-500 uppercase tracking-[0.2em] font-semibold mb-2">Recursos</p>
                  <div className="h-px bg-white/5 mb-3" />
                  <div className="flex flex-wrap gap-2">
                    {liveIdea.resources.map((r: string) => (
                      <Badge key={r} variant="outline" className="border-white/15 text-gray-400 text-xs">
                        {r}
                      </Badge>
                    ))}
                  </div>
                </div>
              )}

              {/* Tags */}
              {liveIdea.tags.length > 0 && (
                <div>
                  <p className="text-[10px] text-gray-500 uppercase tracking-[0.2em] font-semibold mb-2">Tags</p>
                  <div className="h-px bg-white/5 mb-3" />
                  <div className="flex flex-wrap gap-2">
                    {liveIdea.tags.map((t: string) => (
                      <span key={t} className="text-xs px-2.5 py-1 rounded-full bg-[#0126fb]/10 text-[#0126fb]/80 border border-[#0126fb]/20">
                        #{t}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Author section */}
              <div className="flex items-center gap-4 p-4 rounded-xl bg-white/[0.03] border border-white/5">
                <div className="w-11 h-11 rounded-full bg-gradient-to-br from-[#0126fb] to-[#0126fb]/60 flex items-center justify-center text-sm text-white font-bold uppercase flex-shrink-0">
                  {liveIdea.author.name?.charAt(0) || "?"}
                </div>
                <div className="flex-1 min-w-0">
                  <p className="text-white font-semibold text-sm">{liveIdea.author.name}</p>
                  <p className="text-gray-500 text-xs truncate">
                    {liveIdea.author.currentRole?.name || "Membro"} &middot;{" "}
                    {formatDistanceToNow(new Date(liveIdea.createdAt), { addSuffix: true, locale: ptBR })}
                  </p>
                </div>
              </div>

              {/* ====== VOTING SECTION ====== */}
              <div className="rounded-2xl border border-[#f5b719]/20 bg-gradient-to-br from-[#f5b719]/[0.04] to-transparent p-5 space-y-4">
                <div className="flex items-start gap-3">
                  <div className="w-10 h-10 rounded-xl bg-[#f5b719]/10 flex items-center justify-center flex-shrink-0">
                    <Zap className="w-5 h-5 text-[#f5b719]" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <h4 className="text-white font-semibold text-sm">Vote nesta ideia</h4>
                    <p className="text-gray-500 text-xs mt-0.5 leading-relaxed">
                      Seu voto ajuda a priorizar as melhores ideias. Quanto mais votos, maior a visibilidade no ranking do JR Basement.
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <button
                    onClick={() => voteMutation.mutate(liveIdea.id)}
                    disabled={voteMutation.isPending}
                    className={cn(
                      "flex items-center gap-2.5 px-5 py-2.5 rounded-xl font-semibold text-sm transition-all duration-300",
                      liveIdea.votes.some((v: { userId: string }) => v.userId === user?.id)
                        ? "bg-[#f5b719] text-[#010d26] shadow-lg shadow-[#f5b719]/25 hover:shadow-[#f5b719]/40 hover:scale-[1.02]"
                        : "bg-white/5 border border-white/10 text-gray-400 hover:border-[#f5b719]/50 hover:text-[#f5b719] hover:bg-[#f5b719]/5"
                    )}
                  >
                    <Zap className={cn(
                      "w-4 h-4 transition-all",
                      liveIdea.votes.some((v: { userId: string }) => v.userId === user?.id)
                        ? "fill-[#010d26] text-[#010d26]"
                        : ""
                    )} />
                    {liveIdea.votes.some((v: { userId: string }) => v.userId === user?.id) ? "Votado" : "Votar"}
                  </button>

                  <div className="flex items-center gap-2">
                    <span className="text-[#f5b719] font-bold text-xl">{liveIdea.votes.length}</span>
                    <span className="text-gray-500 text-xs">{liveIdea.votes.length === 1 ? "voto" : "votos"}</span>
                  </div>

                  {liveIdea.votes.length > 0 && (
                    <div className="hidden sm:flex items-center -space-x-2 ml-auto">
                      {liveIdea.votes.slice(0, 5).map((v: { userId: string; id: string }, i: number) => (
                        <div
                          key={v.id}
                          className="w-7 h-7 rounded-full bg-gradient-to-br from-[#0126fb] to-[#0126fb]/60 border-2 border-[#010d26] flex items-center justify-center text-[9px] text-white font-bold"
                          style={{ zIndex: 5 - i }}
                        >
                          {i + 1}
                        </div>
                      ))}
                      {liveIdea.votes.length > 5 && (
                        <div className="w-7 h-7 rounded-full bg-white/10 border-2 border-[#010d26] flex items-center justify-center text-[9px] text-gray-400">
                          +{liveIdea.votes.length - 5}
                        </div>
                      )}
                    </div>
                  )}
                </div>
              </div>

              {/* ====== STATUS & MANAGEMENT SECTION ====== */}
              {(() => {
                const isReviewer = canDo(AppAction.REVIEW_INITIATIVES);
                const isOwner = liveIdea.authorId === user?.id;

                if (!isReviewer && !isOwner) return null;

                const availableStatuses = isReviewer
                  ? STATUS_OPTIONS
                  : STATUS_OPTIONS.filter(s => s.value === "DRAFT" || s.value === "SUBMITTED");

                return (
                  <div className="rounded-2xl border border-[#0126fb]/20 bg-gradient-to-br from-[#0126fb]/[0.04] to-transparent p-5 space-y-4">
                    <div className="flex items-start gap-3">
                      <div className="w-10 h-10 rounded-xl bg-[#0126fb]/10 flex items-center justify-center flex-shrink-0">
                        <Shield className="w-5 h-5 text-[#0126fb]" />
                      </div>
                      <div className="flex-1 min-w-0">
                        <h4 className="text-white font-semibold text-sm">
                          {isReviewer ? "Gerenciamento de Status" : "Status da Ideia"}
                        </h4>
                        <p className="text-gray-500 text-xs mt-0.5 leading-relaxed">
                          {isReviewer
                            ? "Como revisor, voce pode alterar o status para qualquer estagio do pipeline de inovacao."
                            : "Voce pode alternar sua ideia entre rascunho e submetida enquanto ela nao for revisada."
                          }
                        </p>
                      </div>
                    </div>

                    <div className="flex flex-wrap items-center gap-3">
                      <div className="flex items-center gap-2">
                        <span className="text-[10px] text-gray-500 uppercase tracking-wider font-medium">Atual:</span>
                        <Badge
                          className={cn(
                            "border text-xs",
                            CLUSTER_STYLES[liveIdea.clusterLevel]?.bg,
                            CLUSTER_STYLES[liveIdea.clusterLevel]?.border,
                            CLUSTER_STYLES[liveIdea.clusterLevel]?.text
                          )}
                        >
                          {STATUS_LABELS[liveIdea.status]}
                        </Badge>
                      </div>

                      <div className="flex items-center gap-2">
                        <ArrowRight className="w-3.5 h-3.5 text-gray-600" />
                        <Select
                          value={liveIdea.status}
                          onValueChange={(v) =>
                            statusMutation.mutate({ ideaId: liveIdea.id, status: v as IdeaStatus })
                          }
                        >
                          <SelectTrigger className="w-[200px] bg-[#00205e]/30 border-[#0126fb]/20 text-white rounded-xl h-10 text-xs font-medium">
                            <SelectValue placeholder="Alterar para..." />
                          </SelectTrigger>
                          <SelectContent className="bg-[#010d26] border-[#0126fb]/20">
                            {availableStatuses.map((opt) => (
                              <SelectItem
                                key={opt.value}
                                value={opt.value}
                                className="text-white hover:!bg-[#0126fb]/20 focus:!bg-[#0126fb]/20"
                              >
                                {opt.label}
                              </SelectItem>
                            ))}
                          </SelectContent>
                        </Select>
                      </div>

                      {statusMutation.isPending && (
                        <div className="flex items-center gap-1.5 text-xs text-gray-400">
                          <div className="w-3.5 h-3.5 border-2 border-[#0126fb] border-t-transparent rounded-full animate-spin" />
                          Atualizando...
                        </div>
                      )}
                    </div>

                    {isReviewer && (
                      <div className="flex flex-wrap gap-1.5 pt-1">
                        <span className="text-[9px] text-gray-600 uppercase tracking-wider">Pipeline:</span>
                        {STATUS_OPTIONS.map((s, i) => (
                          <span key={s.value} className="flex items-center gap-1 text-[9px] text-gray-500">
                            {i > 0 && <span className="text-gray-700">→</span>}
                            <span className={cn(
                              liveIdea.status === s.value ? "text-[#0126fb] font-semibold" : ""
                            )}>
                              {s.label}
                            </span>
                          </span>
                        ))}
                      </div>
                    )}
                  </div>
                );
              })()}

              {/* ====== DELETE ACTION ====== */}
              {liveIdea.authorId === user?.id && (
                <div className="flex items-center justify-between rounded-xl border border-red-500/10 bg-red-500/[0.03] px-5 py-3">
                  <div className="flex items-center gap-2">
                    <Trash2 className="w-4 h-4 text-red-400/60" />
                    <span className="text-xs text-gray-500">Remover esta ideia permanentemente</span>
                  </div>
                  <button
                    onClick={() => {
                      setSelectedIdea(null);
                      setDeleteTarget(liveIdea.id);
                    }}
                    className="text-xs text-red-400 hover:text-red-300 font-medium px-3 py-1.5 rounded-lg hover:bg-red-500/10 transition-all"
                  >
                    Excluir
                  </button>
                </div>
              )}
            </div>
          </DialogContent>
        </Dialog>
        );
      })()}
    </div>
  );
}
